### PR TITLE
Allow bulk selection by holding shift

### PR DESCRIPTION
**Pull request by geveit**
Hi there,

Thanks for the great extension!
I've proposed a small feature to enable selecting multiple checkboxes between the last selection and the current one by holding shift. Your feedback on the pull request would be greatly appreciated.

I also removed a variable "lastChecked" on globals that wasn't being used.

Thanks,
Gabriel

### CODE REVIEW

**Comment by qcrao** [comment]
Thank you so much for your pull request and for the thoughtful improvements you’ve suggested! It’s contributions like yours that help enhance our project and make it more user-friendly.

Selecting Checkboxes in Reverse Order:
The ability to select checkboxes from bottom to top is a great addition. We can implement this by modifying the existing logic to account for the direction of selection—whether the action starts from the end of the list moving upwards. This can be achieved by comparing the indices of the currently and previously checked checkboxes, and adjusting the selection accordingly.

Version Update to 5.0:
I will definitely include the update to version 5.0 as part of this pull request. This version bump reflects the significant enhancements we are incorporating, particularly with the functionalities you've helped introduce.

I am truly grateful for your initiative and support. Please feel free to suggest any more improvements or discuss further enhancements. Looking forward to incorporating these changes and many more, thanks to your help!

Thanks,
qcrao

**Comment by geveit** [comment]
Thanks!
The Reverse Order idea is very good, I'll give it a try.

**Comment by zachpoblete** [comment]
Can this be merged? The version in the Chrome Web Store is already version 5.1.

**Comment by qcrao** [comment]
> Can this be merged? The version in the Chrome Web Store is already version 5.1.

Thanks for attention. I will implement reverse key selection and will merge it later.

**Comment by qcrao** [comment]
@geveit 

I have implemented reserve order multi select and will submit it soon. Thanks for such a good idea.

cc @zachpoblete

**Comment by zachpoblete** [comment]
It works! Thank you.

**Pull request merged**
